version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/es-common
    environment:
      MAVEN_OPTS: -Xmx3200m
      artifact_dir: "tmp/artifacts"

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Build Variables
          command: echo 'export COMMIT_MESSAGE="$(git log --format=oneline -n 1 $CIRCLE_SHA1)"' >> $BASH_ENV

      - run: curl ${GPG_OUT} -o private.key && gpg2 --allow-secret-key-import --import private.key

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run: mvn --settings .ci-settings.xml -DskipTests install
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Start Elastic Docker
          command: docker run -d --name esdocker -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" steeleye/esdocker:5.6.2
      - run:
          name: Maven Verify
          command: mvn --settings .ci-settings.xml -Pemma-coverage -Dassembly.skipAssembly=true verify
      - run:
          name: Stop Elastic Docker
          command: docker rm -f esdocker

      - run:
          name: Collect Test Artifacts
          command: |
            mkdir -p ${artifact_dir}/unit-test/ ${artifact_dir}/integration/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ${artifact_dir}/unit-test/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ${artifact_dir}/integration/ \;
          when: always
      - store_artifacts:
          path: tmp/artifacts

      - deploy:
          name: Maven Deploy
          command: |
            if [[ ${COMMIT_MESSAGE} == *"prepare for release"* ]]; then
                git config user.email "circleci@polyglotted.io"
                git config user.name "CircleCI"
                mvn --settings .ci-settings.xml --batch-mode release:prepare release:perform
            fi